.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright 2014 Kai Pastor (OpenOrienteering)

.TH MAPPER 1 2024-03-31 LibreMapper

.SH NAME
Mapper \- orienteering map drawing software

.SH SYNOPSIS
.B Mapper
.RI [ FILES ]

.SH DESCRIPTION
LibreMapper is an orienteering map drawing software.

.SH OPTIONS
This program takes map file names as options.

.SH AUTHOR
This manual page was written by Kai Pastor <dg0yt@darc.de>.

.SH "REPORTING BUGS"
Report bugs in the LibreMapper ticket system:
.br
<https://github.com/LibreMapper/mapper/issues>

.SH COPYRIGHT
Copyright \(co 2024 The LibreMapper developers
.br
License GPLv3: GNU GPL version 3 <https://www.gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
Extended documentation for
.B Mapper
is available from the program's help menu and its status line.
